# Inspired by
# https://gist.github.com/florentchauveau/2dc4da0299d42258606fc3b0e148fc07#file-gitlab-ci-yml

image: docker:19

services:
  - docker:dind

stages:
  - build
  - push

before_script:
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

Build:
  stage: build
  only:
    refs:
      - pipeline-tests
  script:
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

Push latest:
  stage: push
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - pipeline-tests
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

Push tag:
  stage: push
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - tags
  script:
    # https://gist.github.com/qoomon/22edb16a5e725762f7fdd5083498a64f
    - | # remove leading 'v' for version tags
      if [[ "$CI_COMMIT_TAG" = v[0-9]* ]]; then
        IMAGE_TAG=${IMAGE_TAG#v}
      fi
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
