# Inspired by
# https://gist.github.com/florentchauveau/2dc4da0299d42258606fc3b0e148fc07#file-gitlab-ci-yml

image: docker:19.03.0

services:
  - docker:19.03.0-dind

# https://about.gitlab.com/releases/2019/07/31/docker-in-docker-with-docker-19-dot-03/
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - push

before_script:
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

Build:
  stage: build
  only:
    refs:
      - master
      - tags
  script:
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

Push latest:
  stage: push
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - master
      - tags
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

Push tag:
  stage: push
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - tags
  script:
    # https://gist.github.com/qoomon/22edb16a5e725762f7fdd5083498a64f
    - IMAGE_TAG=$CI_COMMIT_TAG
    - | # remove leading 'v' for version tags
      if [[ "IMAGE_TAG" == v[0-9]* ]]; then
        IMAGE_TAG=${IMAGE_TAG#v}
      fi
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
