stages:
  - build

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/alexanderpetrov/soedini/soedini:latest .
    - docker push $CI_REGISTRY/alexanderpetrov/soedini/soedini:latest
  tags:
    - docker
