# Generated by Django 3.1.4 on 2020-12-17 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('start', 'Start'), ('help', 'Help'), ('cancel', 'Cancel'), ('photo', 'Photo'), ('soedini', 'Soedini'), ('callback', 'Callback'), ('inline', 'Inline')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('started', 'Started'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='started', max_length=10)),
                ('photo_set_finished_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('horizontal', 'Горизонтально'), ('vertical', 'Вертикально'), ('two_rows', '2 ряда'), ('square', 'Квадрат')], default='horizontal', max_length=15)),
                ('control_telegram_message_id', models.IntegerField(blank=True, null=True)),
                ('control_telegram_message_sent_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.session')),
            ],
        ),
        migrations.CreateModel(
            name='ModeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('horizontal', 'Горизонтально'), ('vertical', 'Вертикально'), ('two_rows', '2 ряда'), ('square', 'Квадрат')], max_length=15)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.session')),
            ],
        ),
    ]
