# Generated by Django 3.1.4 on 2020-12-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='telegram_photo_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
