# Generated by Django 3.1.4 on 2020-12-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_session_query_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='query_hash',
        ),
        migrations.AddField(
            model_name='session',
            name='query_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
