# Generated by Django 3.1.4 on 2020-12-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20201218_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='query_token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
